services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    ports:
      - 9117:9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/storage/jackett:/config/Jackett
      - ~/downloads:/downloads
    networks:
      - cheeselab

networks:
  cheeselab:
    external: true