services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/lidarr/config:/config
      - /mnt/storage-hdd/Media/Music:/music
      - ~/downloads:/downloads
    ports:
      - 8686:8686
    networks:
      - cheeselab
    restart: unless-stopped

networks:
  cheeselab:
    external: true