services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Dublin
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - ~/storage/overseerr:/app/config
    networks:
      - cheeselab
    restart: unless-stopped

networks:
  cheeselab:
    external: true
