services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      DISK_SIZE: "64G"
      RAM_SIZE: "4G"
      CPU_CORES: "3"
      USERNAME: $USERNAME
      PASSWORD: $PASSWORD
      LANGUAGE: "English"
      REGION: "en-GB"
      KEYBOARD: "en-GB"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ~/storage/windows:/storage
    restart: always
    stop_grace_period: 2m