services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=3001
    volumes:
      - /home/jake/services/qbittorrent/config:/config
      - /home/jake/downloads:/downloads
    ports:
      - 3001:3001
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
