services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=3001
      - TORRENTING_PORT=6881
    volumes:
      - ~/storage/qbittorrent/config:/config
      - ~/storage/qbittorrent/downloads:/downloads
    ports:
      - 3001:3001
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
