services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "3002:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Europe/Dublin'
      PIHOLE_DNS_: '8.8.8.8;8.8.4.4'
      WEBTHEME: 'default-darker'
    volumes:
      - '~/storage/pi-hole/etc-pihole:/etc/pihole'
      - '~/storage/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    env_file:
     - path: /home/jake/services/pi-hole/.env