services:
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli
    restart: unless-stopped
    volumes:
      - ~/storage/tautulli:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8181:8181
    networks:
      - cheeselab

networks:
  cheeselab:
    external: true