services:
    speedtest-tracker:
        container_name: speedtest-tracker
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /home/jake/services/speedtest-tracker/config:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.speedtest-tracker.entrypoints=https"
            - "traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.local.jakefarrell.ie`)"

networks:
  default:
    name: traefik_net
    external: true