services:
  cable-anarchy-minecraft:
    image: itzg/minecraft-server
    container_name: cable-anarchy-minecraft
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 2G
    ports:
      - "25565:25565"
    volumes:
      - ~/storage/cable-anarchy-minecraft:/data
    restart: unless-stopped
