services:
  wiki-dcu-lol:
    image: mediawiki
    hostname: wiki-dcu-lol
    container_name: wiki-dcu-lol
    restart: unless-stopped
    volumes:
      - ~/storage/wiki-dcu-lol/LocalSettings.php:/var/www/html/LocalSettings.php
      - database:/var/www/data
      - ~/storage/wiki-dcu-lol/images:/var/www/html/images
      - ~/storage/wiki-dcu-lol/deleted_files:/var/www/html/deleted_files
    ports:
      - 8084:80
      
volumes:
  database:
  images:
  deleted_files: