services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    hostname: photoprism
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - photoprism-database
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: ${PHOTOPRISM_ADMIN_USER}
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DEFAULT_TLS: "true"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_VECTORS: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: ${PHOTOPRISM_DATABASE_SERVER}
      PHOTOPRISM_DATABASE_NAME: ${PHOTOPRISM_DATABASE_NAME}
      PHOTOPRISM_DATABASE_USER: ${PHOTOPRISM_DATABASE_USER}
      PHOTOPRISM_DATABASE_PASSWORD: ${PHOTOPRISM_DATABASE_PASSWORD}
      PHOTOPRISM_SITE_CAPTION: "CheeseLad's Photo Collection"
      PHOTOPRISM_SITE_DESCRIPTION: "CheeseLad's Photo Collection"
      PHOTOPRISM_SITE_AUTHOR: "CheeseLad"
    working_dir: "/photoprism"
    volumes:
      - "~/Pictures:/photoprism/originals"
      - "./storage:/photoprism/storage"
      - "/mnt/usb1/Photos & Videos/ME173X:/photoprism/originals/me173x"
      - "/mnt/usb1/Photos & Videos/Xperia XA:/photoprism/originals/xperia-xa"
      - "/mnt/usb1/Photos & Videos/Jake’s iPhone 13 Pro:/photoprism/originals/jakes-iphone-13-pro"
      - "/mnt/usb1/Photos & Videos/Galaxy A70:/photoprism/originals/galaxy-a70"

  photoprism-database:
    image: mariadb:11
    container_name: photoprism-database
    hostname: photoprism-database
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: ${PHOTOPRISM_DATABASE_NAME}
      MARIADB_USER: ${PHOTOPRISM_DATABASE_USER}
      MARIADB_PASSWORD: ${PHOTOPRISM_DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${PHOTOPRISM_DATABASE_ROOT_PASSWORD}
