services:
  cable-creative-roleplay:
    container_name: cable-creative-roleplay
    hostname: cable-creative-roleplay
    image: imperialplugins/unturned
    restart: unless-stopped
    environment:
      - SERVER_TYPE=rm4
    ports:
      - 27015:27015
      - 27016:27016
    volumes:
      - ./data:/home/steam/Unturned