services:
  unturned_update:
    container_name: cable-creative-roleplay-update
    image: steamcmd/steamcmd:ubuntu-22
    volumes:
      - ~/storage/cable-creative-roleplay:/app
    command: [
      "+force_install_dir", "/app",
      "+login", "anonymous",
      "+app_update", "1110390",
      "validate",
      "+quit"
    ]
  unturned_srv:
    container_name: cable-creative-roleplay
    build:
      context: .
    volumes:
      - ~/storage/cable-creative-roleplay:/app
    ports:
      - 27015-27016:27015-27016/udp
    stdin_open: true
      #equivalent to docker run -i
    tty: true
      #equivalent to docker run -t
    restart: unless-stopped
    command: +secureserver/unturned