services:
  cable-creative-roleplay:
    container_name: cable-creative-roleplay
    hostname: cable-creative-roleplay
    image: imperialplugins/unturned
    restart: unless-stopped
    environment:
      - SERVER_TYPE=rm4
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
      - 27017:27017/udp
    volumes:
      - ./data:/home/steam/Unturned