services:
  tcvapp:
    image: nginx:latest
    container_name: tcvapp
    restart: unless-stopped
    volumes:
      - ~/storage/tcvapp:/usr/share/nginx/html
    ports:
      - "3023:80"
    networks:
      - cheeselab

networks:
  cheeselab:
    external: true