services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-http.rule=Host(`nginx.local.jakefarrell.ie`)
      - traefik.http.routers.nginx-http.entrypoints=web

networks:
  traefik:
    external: true