services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8545:8000"
    volumes:
      - ./config/data:/usr/src/paperless/data
      - ./config/media:/usr/src/paperless/media
      - ./config/export:/usr/src/paperless/export
      - ./config/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379

volumes:
  data:
  media:
  redisdata: