---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://192.168.1.2
    volumes:
      - ~/storage/jellyfin:/config
      - /mnt/usb1/Plex:/media
      - /mnt/usb2/Plex:/media2
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
     # - 1900:1900/udp
    networks:
      - cheeselab
    restart: unless-stopped

networks:
  cheeselab:
    external: true