services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ~/storage/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_URL="https://status.jakefarrell.ie"
    ports:
      - 3003:3001
    restart: unless-stopped
    networks:
      - cheeselab

networks:
  cheeselab:
    external: true