services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/radarr:/config
      - /mnt/storage-hdd/Media/Movies:/movies
      - ~/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - cheeselab
    restart: unless-stopped

networks:
  cheeselab:
    external: true