services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/radarr:/config
      - /mnt/usb2/Plex/Movies:/movies
      - /home/jake/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped