services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/storage/sonarr:/config
      - /mnt/usb2/Plex/Series:/tv
      - ~/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
