version: "2"
services:
plex:
image: linuxserver/plex
container_name: plex
network_mode: host
environment:
- PUID=1001 
- PGID=1001 
- VERSION=docker
volumes:
- /docker/plex/library:/config
- /media/plex/tvseries:/tv
- /media/plex/movies:/movies
restart: always