services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Dublin
    ports:
      - 8191:8191
    networks:
      - cheeselab
    restart: unless-stopped

networks:
  cheeselab:
    external: true
